// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEdCzN8RI9eZvrwrXA_l4xFRtFxy3aZB0',
    appId: '1:749926104874:web:47be59553355d09b126853',
    messagingSenderId: '749926104874',
    projectId: 'signup-login-e7e0a',
    authDomain: 'signup-login-e7e0a.firebaseapp.com',
    storageBucket: 'signup-login-e7e0a.appspot.com',
    measurementId: 'G-FN07S8K8GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhe-y6G-kIh3OYuFo4HehLpKXo6RYblOI',
    appId: '1:749926104874:android:19d14a8155c96487126853',
    messagingSenderId: '749926104874',
    projectId: 'signup-login-e7e0a',
    storageBucket: 'signup-login-e7e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzh_QgelXjcr7KiNIbP1_b6z5Xv0ezc1U',
    appId: '1:749926104874:ios:15e8d13bcc166018126853',
    messagingSenderId: '749926104874',
    projectId: 'signup-login-e7e0a',
    storageBucket: 'signup-login-e7e0a.appspot.com',
    iosClientId: '749926104874-8n7527eehcvojhm5d61mbtt6eveetevd.apps.googleusercontent.com',
    iosBundleId: 'com.example.billingfirebase',
  );
}
